// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: dcrpc.proto

package dcrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_dcrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_dcrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type SetLocalhostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Area          string                 `protobuf:"bytes,4,opt,name=Area,proto3" json:"Area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLocalhostRequest) Reset() {
	*x = SetLocalhostRequest{}
	mi := &file_dcrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLocalhostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocalhostRequest) ProtoMessage() {}

func (x *SetLocalhostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocalhostRequest.ProtoReflect.Descriptor instead.
func (*SetLocalhostRequest) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{2}
}

func (x *SetLocalhostRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetLocalhostRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SetLocalhostRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SetLocalhostRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

type SetLocalhostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLocalhostResponse) Reset() {
	*x = SetLocalhostResponse{}
	mi := &file_dcrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLocalhostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocalhostResponse) ProtoMessage() {}

func (x *SetLocalhostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocalhostResponse.ProtoReflect.Descriptor instead.
func (*SetLocalhostResponse) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{3}
}

func (x *SetLocalhostResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetLocalhostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocalhostRequest) Reset() {
	*x = GetLocalhostRequest{}
	mi := &file_dcrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocalhostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocalhostRequest) ProtoMessage() {}

func (x *GetLocalhostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocalhostRequest.ProtoReflect.Descriptor instead.
func (*GetLocalhostRequest) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetLocalhostRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetLocalhostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocalhostResponse) Reset() {
	*x = GetLocalhostResponse{}
	mi := &file_dcrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocalhostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocalhostResponse) ProtoMessage() {}

func (x *GetLocalhostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocalhostResponse.ProtoReflect.Descriptor instead.
func (*GetLocalhostResponse) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetLocalhostResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetLocalhostResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetLocalhostResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// 请求：传入两个地点名称和距离单位
type CalcDistanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderCode     string                 `protobuf:"bytes,1,opt,name=OrderCode,proto3" json:"OrderCode,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,3,opt,name=OrderStatus,proto3" json:"OrderStatus,omitempty"`
	PassengerId   int64                  `protobuf:"varint,4,opt,name=PassengerId,proto3" json:"PassengerId,omitempty"`
	StartAddr     string                 `protobuf:"bytes,5,opt,name=StartAddr,proto3" json:"StartAddr,omitempty"`
	EndEnd        string                 `protobuf:"bytes,6,opt,name=EndEnd,proto3" json:"EndEnd,omitempty"`
	DriverId      int64                  `protobuf:"varint,7,opt,name=DriverId,proto3" json:"DriverId,omitempty"`
	FromName      string                 `protobuf:"bytes,15,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"` // 起点名称，例如 "上海"
	ToName        string                 `protobuf:"bytes,16,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`       // 终点名称，例如 "北京"
	Unit          string                 `protobuf:"bytes,17,opt,name=unit,proto3" json:"unit,omitempty"`                         // 距离单位，"m"、"km"、"mi" 等
	TripKey       string                 `protobuf:"bytes,18,opt,name=TripKey,proto3" json:"TripKey,omitempty"`
	DriverKey     string                 `protobuf:"bytes,19,opt,name=DriverKey,proto3" json:"DriverKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcDistanceRequest) Reset() {
	*x = CalcDistanceRequest{}
	mi := &file_dcrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcDistanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcDistanceRequest) ProtoMessage() {}

func (x *CalcDistanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcDistanceRequest.ProtoReflect.Descriptor instead.
func (*CalcDistanceRequest) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{6}
}

func (x *CalcDistanceRequest) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

func (x *CalcDistanceRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CalcDistanceRequest) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *CalcDistanceRequest) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

func (x *CalcDistanceRequest) GetStartAddr() string {
	if x != nil {
		return x.StartAddr
	}
	return ""
}

func (x *CalcDistanceRequest) GetEndEnd() string {
	if x != nil {
		return x.EndEnd
	}
	return ""
}

func (x *CalcDistanceRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *CalcDistanceRequest) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *CalcDistanceRequest) GetToName() string {
	if x != nil {
		return x.ToName
	}
	return ""
}

func (x *CalcDistanceRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *CalcDistanceRequest) GetTripKey() string {
	if x != nil {
		return x.TripKey
	}
	return ""
}

func (x *CalcDistanceRequest) GetDriverKey() string {
	if x != nil {
		return x.DriverKey
	}
	return ""
}

// 返回：两地之间的距离值
type CalcDistanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      float64                `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"` // 计算出的距离
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcDistanceResponse) Reset() {
	*x = CalcDistanceResponse{}
	mi := &file_dcrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcDistanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcDistanceResponse) ProtoMessage() {}

func (x *CalcDistanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcDistanceResponse.ProtoReflect.Descriptor instead.
func (*CalcDistanceResponse) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{7}
}

func (x *CalcDistanceResponse) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type NearbyDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`   // 乘客当前纬度
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"` // 乘客当前经度
	Radius        float64                `protobuf:"fixed64,3,opt,name=radius,proto3" json:"radius,omitempty"`       // 搜索半径
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`          // 最多返回多少个司机
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`             // 距离单位，m/km/mi，默认 km
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyDriversRequest) Reset() {
	*x = NearbyDriversRequest{}
	mi := &file_dcrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyDriversRequest) ProtoMessage() {}

func (x *NearbyDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyDriversRequest.ProtoReflect.Descriptor instead.
func (*NearbyDriversRequest) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{8}
}

func (x *NearbyDriversRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *NearbyDriversRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *NearbyDriversRequest) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *NearbyDriversRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *NearbyDriversRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type Driver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 可选：司机昵称
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Distance      float64                `protobuf:"fixed64,5,opt,name=distance,proto3" json:"distance,omitempty"` // 与乘客的距离
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_dcrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{9}
}

func (x *Driver) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *Driver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Driver) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Driver) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Driver) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type NearbyDriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*Driver              `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyDriversResponse) Reset() {
	*x = NearbyDriversResponse{}
	mi := &file_dcrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyDriversResponse) ProtoMessage() {}

func (x *NearbyDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyDriversResponse.ProtoReflect.Descriptor instead.
func (*NearbyDriversResponse) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{10}
}

func (x *NearbyDriversResponse) GetDrivers() []*Driver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

type AmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	DriverId      int64                  `protobuf:"varint,2,opt,name=DriverId,proto3" json:"DriverId,omitempty"`
	FromName      string                 `protobuf:"bytes,3,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"` // 起点名称，例如 "上海"
	ToName        string                 `protobuf:"bytes,4,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`       // 终点名称，例如 "北京"
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`                         // 距离单位，"m"、"km"、"mi" 等
	Distance      float64                `protobuf:"fixed64,6,opt,name=distance,proto3" json:"distance,omitempty"`               // 与乘客的距离
	Id            int64                  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`                            // 与乘客的距离
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmountRequest) Reset() {
	*x = AmountRequest{}
	mi := &file_dcrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmountRequest) ProtoMessage() {}

func (x *AmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmountRequest.ProtoReflect.Descriptor instead.
func (*AmountRequest) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{11}
}

func (x *AmountRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AmountRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *AmountRequest) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *AmountRequest) GetToName() string {
	if x != nil {
		return x.ToName
	}
	return ""
}

func (x *AmountRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *AmountRequest) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *AmountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 返回：两地之间的距离值
type AmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      float64                `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"` // 计算出的距离
	TotalAmount   float64                `protobuf:"fixed64,2,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmountResponse) Reset() {
	*x = AmountResponse{}
	mi := &file_dcrpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmountResponse) ProtoMessage() {}

func (x *AmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmountResponse.ProtoReflect.Descriptor instead.
func (*AmountResponse) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{12}
}

func (x *AmountResponse) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *AmountResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TotalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,2,opt,name=DriverId,proto3" json:"DriverId,omitempty"`
	PayStatus     int64                  `protobuf:"varint,3,opt,name=PayStatus,proto3" json:"PayStatus,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	EndAt         string                 `protobuf:"bytes,5,opt,name=EndAt,proto3" json:"EndAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalRequest) Reset() {
	*x = TotalRequest{}
	mi := &file_dcrpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalRequest) ProtoMessage() {}

func (x *TotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalRequest.ProtoReflect.Descriptor instead.
func (*TotalRequest) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{13}
}

func (x *TotalRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *TotalRequest) GetPayStatus() int64 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *TotalRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TotalRequest) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

type TotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float32                `protobuf:"fixed32,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalResponse) Reset() {
	*x = TotalResponse{}
	mi := &file_dcrpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalResponse) ProtoMessage() {}

func (x *TotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalResponse.ProtoReflect.Descriptor instead.
func (*TotalResponse) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{14}
}

func (x *TotalResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TotalResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ReceiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PickupId      int64                  `protobuf:"varint,2,opt,name=PickupId,proto3" json:"PickupId,omitempty"`
	OrderId       int64                  `protobuf:"varint,3,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	DriverId      int64                  `protobuf:"varint,4,opt,name=DriverId,proto3" json:"DriverId,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRequest) Reset() {
	*x = ReceiveRequest{}
	mi := &file_dcrpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRequest) ProtoMessage() {}

func (x *ReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{15}
}

func (x *ReceiveRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReceiveRequest) GetPickupId() int64 {
	if x != nil {
		return x.PickupId
	}
	return 0
}

func (x *ReceiveRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReceiveRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *ReceiveRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReceiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveResponse) Reset() {
	*x = ReceiveResponse{}
	mi := &file_dcrpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveResponse) ProtoMessage() {}

func (x *ReceiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveResponse.ProtoReflect.Descriptor instead.
func (*ReceiveResponse) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{16}
}

func (x *ReceiveResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type EndOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PickupId      int64                  `protobuf:"varint,2,opt,name=PickupId,proto3" json:"PickupId,omitempty"`
	OrderId       int64                  `protobuf:"varint,3,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	DriverId      int64                  `protobuf:"varint,4,opt,name=DriverId,proto3" json:"DriverId,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndOrderRequest) Reset() {
	*x = EndOrderRequest{}
	mi := &file_dcrpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndOrderRequest) ProtoMessage() {}

func (x *EndOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndOrderRequest.ProtoReflect.Descriptor instead.
func (*EndOrderRequest) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{17}
}

func (x *EndOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EndOrderRequest) GetPickupId() int64 {
	if x != nil {
		return x.PickupId
	}
	return 0
}

func (x *EndOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *EndOrderRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *EndOrderRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EndOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndOrderResponse) Reset() {
	*x = EndOrderResponse{}
	mi := &file_dcrpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndOrderResponse) ProtoMessage() {}

func (x *EndOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndOrderResponse.ProtoReflect.Descriptor instead.
func (*EndOrderResponse) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{18}
}

func (x *EndOrderResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MongoDBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeoKey        string                 `protobuf:"bytes,1,opt,name=GeoKey,proto3" json:"GeoKey,omitempty"`       // Redis 中 GEO 的 key（例如："drivers"）
	DriverIds     []string               `protobuf:"bytes,2,rep,name=DriverIds,proto3" json:"DriverIds,omitempty"` // 需要同步到 MongoDB 的 driverId 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MongoDBRequest) Reset() {
	*x = MongoDBRequest{}
	mi := &file_dcrpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoDBRequest) ProtoMessage() {}

func (x *MongoDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoDBRequest.ProtoReflect.Descriptor instead.
func (*MongoDBRequest) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{19}
}

func (x *MongoDBRequest) GetGeoKey() string {
	if x != nil {
		return x.GeoKey
	}
	return ""
}

func (x *MongoDBRequest) GetDriverIds() []string {
	if x != nil {
		return x.DriverIds
	}
	return nil
}

type MongoDBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       int64                  `protobuf:"varint,1,opt,name=Updated,proto3" json:"Updated,omitempty"`    // 成功 upsert 的数量
	FailedIds     []string               `protobuf:"bytes,2,rep,name=FailedIds,proto3" json:"FailedIds,omitempty"` // 写入失败的 driverId 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MongoDBResponse) Reset() {
	*x = MongoDBResponse{}
	mi := &file_dcrpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoDBResponse) ProtoMessage() {}

func (x *MongoDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoDBResponse.ProtoReflect.Descriptor instead.
func (*MongoDBResponse) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{20}
}

func (x *MongoDBResponse) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *MongoDBResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

type CityLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityLocation) Reset() {
	*x = CityLocation{}
	mi := &file_dcrpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityLocation) ProtoMessage() {}

func (x *CityLocation) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityLocation.ProtoReflect.Descriptor instead.
func (*CityLocation) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{21}
}

func (x *CityLocation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CityLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CityLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type MonDBCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cities        []*CityLocation        `protobuf:"bytes,1,rep,name=Cities,proto3" json:"Cities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonDBCreateRequest) Reset() {
	*x = MonDBCreateRequest{}
	mi := &file_dcrpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonDBCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonDBCreateRequest) ProtoMessage() {}

func (x *MonDBCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonDBCreateRequest.ProtoReflect.Descriptor instead.
func (*MonDBCreateRequest) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{22}
}

func (x *MonDBCreateRequest) GetCities() []*CityLocation {
	if x != nil {
		return x.Cities
	}
	return nil
}

type MonDBCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      int32                  `protobuf:"varint,1,opt,name=Inserted,proto3" json:"Inserted,omitempty"` // 插入成功数量
	Failed        []string               `protobuf:"bytes,2,rep,name=Failed,proto3" json:"Failed,omitempty"`      // 插入失败的城市名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonDBCreateResponse) Reset() {
	*x = MonDBCreateResponse{}
	mi := &file_dcrpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonDBCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonDBCreateResponse) ProtoMessage() {}

func (x *MonDBCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcrpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonDBCreateResponse.ProtoReflect.Descriptor instead.
func (*MonDBCreateResponse) Descriptor() ([]byte, []int) {
	return file_dcrpc_proto_rawDescGZIP(), []int{23}
}

func (x *MonDBCreateResponse) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

func (x *MonDBCreateResponse) GetFailed() []string {
	if x != nil {
		return x.Failed
	}
	return nil
}

var File_dcrpc_proto protoreflect.FileDescriptor

const file_dcrpc_proto_rawDesc = "" +
	"\n" +
	"\vdcrpc.proto\x12\x05dcrpc\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"w\n" +
	"\x13SetLocalhostRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1a\n" +
	"\bLatitude\x18\x02 \x01(\x01R\bLatitude\x12\x1c\n" +
	"\tLongitude\x18\x03 \x01(\x01R\tLongitude\x12\x12\n" +
	"\x04Area\x18\x04 \x01(\tR\x04Area\"(\n" +
	"\x14SetLocalhostResponse\x12\x10\n" +
	"\x03Msg\x18\x01 \x01(\tR\x03Msg\")\n" +
	"\x13GetLocalhostRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"d\n" +
	"\x14GetLocalhostResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"\xe3\x02\n" +
	"\x13CalcDistanceRequest\x12\x1c\n" +
	"\tOrderCode\x18\x01 \x01(\tR\tOrderCode\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x02R\x06Amount\x12 \n" +
	"\vOrderStatus\x18\x03 \x01(\tR\vOrderStatus\x12 \n" +
	"\vPassengerId\x18\x04 \x01(\x03R\vPassengerId\x12\x1c\n" +
	"\tStartAddr\x18\x05 \x01(\tR\tStartAddr\x12\x16\n" +
	"\x06EndEnd\x18\x06 \x01(\tR\x06EndEnd\x12\x1a\n" +
	"\bDriverId\x18\a \x01(\x03R\bDriverId\x12\x1b\n" +
	"\tfrom_name\x18\x0f \x01(\tR\bfromName\x12\x17\n" +
	"\ato_name\x18\x10 \x01(\tR\x06toName\x12\x12\n" +
	"\x04unit\x18\x11 \x01(\tR\x04unit\x12\x18\n" +
	"\aTripKey\x18\x12 \x01(\tR\aTripKey\x12\x1c\n" +
	"\tDriverKey\x18\x13 \x01(\tR\tDriverKey\"2\n" +
	"\x14CalcDistanceResponse\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\x01R\bdistance\"\x92\x01\n" +
	"\x14NearbyDriversRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x01R\x06radius\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\"\x8f\x01\n" +
	"\x06Driver\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bdistance\x18\x05 \x01(\x01R\bdistance\"@\n" +
	"\x15NearbyDriversResponse\x12'\n" +
	"\adrivers\x18\x01 \x03(\v2\r.dcrpc.DriverR\adrivers\"\xb9\x01\n" +
	"\rAmountRequest\x12\x16\n" +
	"\x06Amount\x18\x01 \x01(\x01R\x06Amount\x12\x1a\n" +
	"\bDriverId\x18\x02 \x01(\x03R\bDriverId\x12\x1b\n" +
	"\tfrom_name\x18\x03 \x01(\tR\bfromName\x12\x17\n" +
	"\ato_name\x18\x04 \x01(\tR\x06toName\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12\x1a\n" +
	"\bdistance\x18\x06 \x01(\x01R\bdistance\x12\x0e\n" +
	"\x02id\x18\a \x01(\x03R\x02id\"N\n" +
	"\x0eAmountResponse\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\x01R\bdistance\x12 \n" +
	"\vTotalAmount\x18\x02 \x01(\x01R\vTotalAmount\"|\n" +
	"\fTotalRequest\x12\x1a\n" +
	"\bDriverId\x18\x02 \x01(\x03R\bDriverId\x12\x1c\n" +
	"\tPayStatus\x18\x03 \x01(\x03R\tPayStatus\x12\x1c\n" +
	"\tCreatedAt\x18\x04 \x01(\tR\tCreatedAt\x12\x14\n" +
	"\x05EndAt\x18\x05 \x01(\tR\x05EndAt\"9\n" +
	"\rTotalResponse\x12\x16\n" +
	"\x06Amount\x18\x01 \x01(\x02R\x06Amount\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"\x8a\x01\n" +
	"\x0eReceiveRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x1a\n" +
	"\bPickupId\x18\x02 \x01(\x03R\bPickupId\x12\x18\n" +
	"\aOrderId\x18\x03 \x01(\x03R\aOrderId\x12\x1a\n" +
	"\bDriverId\x18\x04 \x01(\x03R\bDriverId\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\tR\x06Status\"#\n" +
	"\x0fReceiveResponse\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"\x8b\x01\n" +
	"\x0fEndOrderRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x1a\n" +
	"\bPickupId\x18\x02 \x01(\x03R\bPickupId\x12\x18\n" +
	"\aOrderId\x18\x03 \x01(\x03R\aOrderId\x12\x1a\n" +
	"\bDriverId\x18\x04 \x01(\x03R\bDriverId\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\tR\x06Status\"$\n" +
	"\x10EndOrderResponse\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"F\n" +
	"\x0eMongoDBRequest\x12\x16\n" +
	"\x06GeoKey\x18\x01 \x01(\tR\x06GeoKey\x12\x1c\n" +
	"\tDriverIds\x18\x02 \x03(\tR\tDriverIds\"I\n" +
	"\x0fMongoDBResponse\x12\x18\n" +
	"\aUpdated\x18\x01 \x01(\x03R\aUpdated\x12\x1c\n" +
	"\tFailedIds\x18\x02 \x03(\tR\tFailedIds\"\\\n" +
	"\fCityLocation\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1a\n" +
	"\bLatitude\x18\x02 \x01(\x01R\bLatitude\x12\x1c\n" +
	"\tLongitude\x18\x03 \x01(\x01R\tLongitude\"A\n" +
	"\x12MonDBCreateRequest\x12+\n" +
	"\x06Cities\x18\x01 \x03(\v2\x13.dcrpc.CityLocationR\x06Cities\"I\n" +
	"\x13MonDBCreateResponse\x12\x1a\n" +
	"\bInserted\x18\x01 \x01(\x05R\bInserted\x12\x16\n" +
	"\x06Failed\x18\x02 \x03(\tR\x06Failed2\xb9\x05\n" +
	"\x05Dcrpc\x12'\n" +
	"\x04Ping\x12\x0e.dcrpc.Request\x1a\x0f.dcrpc.Response\x12G\n" +
	"\fSetLocalhost\x12\x1a.dcrpc.SetLocalhostRequest\x1a\x1b.dcrpc.SetLocalhostResponse\x12G\n" +
	"\fGetLocalhost\x12\x1a.dcrpc.GetLocalhostRequest\x1a\x1b.dcrpc.GetLocalhostResponse\x12G\n" +
	"\fCalcDistance\x12\x1a.dcrpc.CalcDistanceRequest\x1a\x1b.dcrpc.CalcDistanceResponse\x12J\n" +
	"\rNearbyDrivers\x12\x1b.dcrpc.NearbyDriversRequest\x1a\x1c.dcrpc.NearbyDriversResponse\x125\n" +
	"\x06Amount\x12\x14.dcrpc.AmountRequest\x1a\x15.dcrpc.AmountResponse\x128\n" +
	"\aMongoDB\x12\x15.dcrpc.MongoDBRequest\x1a\x16.dcrpc.MongoDBResponse\x122\n" +
	"\x05Total\x12\x13.dcrpc.TotalRequest\x1a\x14.dcrpc.TotalResponse\x128\n" +
	"\aReceive\x12\x15.dcrpc.ReceiveRequest\x1a\x16.dcrpc.ReceiveResponse\x12;\n" +
	"\bEndOrder\x12\x16.dcrpc.EndOrderRequest\x1a\x17.dcrpc.EndOrderResponse\x12D\n" +
	"\vMonDBCreate\x12\x19.dcrpc.MonDBCreateRequest\x1a\x1a.dcrpc.MonDBCreateResponseB\tZ\a./dcrpcb\x06proto3"

var (
	file_dcrpc_proto_rawDescOnce sync.Once
	file_dcrpc_proto_rawDescData []byte
)

func file_dcrpc_proto_rawDescGZIP() []byte {
	file_dcrpc_proto_rawDescOnce.Do(func() {
		file_dcrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dcrpc_proto_rawDesc), len(file_dcrpc_proto_rawDesc)))
	})
	return file_dcrpc_proto_rawDescData
}

var file_dcrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_dcrpc_proto_goTypes = []any{
	(*Request)(nil),               // 0: dcrpc.Request
	(*Response)(nil),              // 1: dcrpc.Response
	(*SetLocalhostRequest)(nil),   // 2: dcrpc.SetLocalhostRequest
	(*SetLocalhostResponse)(nil),  // 3: dcrpc.SetLocalhostResponse
	(*GetLocalhostRequest)(nil),   // 4: dcrpc.GetLocalhostRequest
	(*GetLocalhostResponse)(nil),  // 5: dcrpc.GetLocalhostResponse
	(*CalcDistanceRequest)(nil),   // 6: dcrpc.CalcDistanceRequest
	(*CalcDistanceResponse)(nil),  // 7: dcrpc.CalcDistanceResponse
	(*NearbyDriversRequest)(nil),  // 8: dcrpc.NearbyDriversRequest
	(*Driver)(nil),                // 9: dcrpc.Driver
	(*NearbyDriversResponse)(nil), // 10: dcrpc.NearbyDriversResponse
	(*AmountRequest)(nil),         // 11: dcrpc.AmountRequest
	(*AmountResponse)(nil),        // 12: dcrpc.AmountResponse
	(*TotalRequest)(nil),          // 13: dcrpc.TotalRequest
	(*TotalResponse)(nil),         // 14: dcrpc.TotalResponse
	(*ReceiveRequest)(nil),        // 15: dcrpc.ReceiveRequest
	(*ReceiveResponse)(nil),       // 16: dcrpc.ReceiveResponse
	(*EndOrderRequest)(nil),       // 17: dcrpc.EndOrderRequest
	(*EndOrderResponse)(nil),      // 18: dcrpc.EndOrderResponse
	(*MongoDBRequest)(nil),        // 19: dcrpc.MongoDBRequest
	(*MongoDBResponse)(nil),       // 20: dcrpc.MongoDBResponse
	(*CityLocation)(nil),          // 21: dcrpc.CityLocation
	(*MonDBCreateRequest)(nil),    // 22: dcrpc.MonDBCreateRequest
	(*MonDBCreateResponse)(nil),   // 23: dcrpc.MonDBCreateResponse
}
var file_dcrpc_proto_depIdxs = []int32{
	9,  // 0: dcrpc.NearbyDriversResponse.drivers:type_name -> dcrpc.Driver
	21, // 1: dcrpc.MonDBCreateRequest.Cities:type_name -> dcrpc.CityLocation
	0,  // 2: dcrpc.Dcrpc.Ping:input_type -> dcrpc.Request
	2,  // 3: dcrpc.Dcrpc.SetLocalhost:input_type -> dcrpc.SetLocalhostRequest
	4,  // 4: dcrpc.Dcrpc.GetLocalhost:input_type -> dcrpc.GetLocalhostRequest
	6,  // 5: dcrpc.Dcrpc.CalcDistance:input_type -> dcrpc.CalcDistanceRequest
	8,  // 6: dcrpc.Dcrpc.NearbyDrivers:input_type -> dcrpc.NearbyDriversRequest
	11, // 7: dcrpc.Dcrpc.Amount:input_type -> dcrpc.AmountRequest
	19, // 8: dcrpc.Dcrpc.MongoDB:input_type -> dcrpc.MongoDBRequest
	13, // 9: dcrpc.Dcrpc.Total:input_type -> dcrpc.TotalRequest
	15, // 10: dcrpc.Dcrpc.Receive:input_type -> dcrpc.ReceiveRequest
	17, // 11: dcrpc.Dcrpc.EndOrder:input_type -> dcrpc.EndOrderRequest
	22, // 12: dcrpc.Dcrpc.MonDBCreate:input_type -> dcrpc.MonDBCreateRequest
	1,  // 13: dcrpc.Dcrpc.Ping:output_type -> dcrpc.Response
	3,  // 14: dcrpc.Dcrpc.SetLocalhost:output_type -> dcrpc.SetLocalhostResponse
	5,  // 15: dcrpc.Dcrpc.GetLocalhost:output_type -> dcrpc.GetLocalhostResponse
	7,  // 16: dcrpc.Dcrpc.CalcDistance:output_type -> dcrpc.CalcDistanceResponse
	10, // 17: dcrpc.Dcrpc.NearbyDrivers:output_type -> dcrpc.NearbyDriversResponse
	12, // 18: dcrpc.Dcrpc.Amount:output_type -> dcrpc.AmountResponse
	20, // 19: dcrpc.Dcrpc.MongoDB:output_type -> dcrpc.MongoDBResponse
	14, // 20: dcrpc.Dcrpc.Total:output_type -> dcrpc.TotalResponse
	16, // 21: dcrpc.Dcrpc.Receive:output_type -> dcrpc.ReceiveResponse
	18, // 22: dcrpc.Dcrpc.EndOrder:output_type -> dcrpc.EndOrderResponse
	23, // 23: dcrpc.Dcrpc.MonDBCreate:output_type -> dcrpc.MonDBCreateResponse
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_dcrpc_proto_init() }
func file_dcrpc_proto_init() {
	if File_dcrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dcrpc_proto_rawDesc), len(file_dcrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dcrpc_proto_goTypes,
		DependencyIndexes: file_dcrpc_proto_depIdxs,
		MessageInfos:      file_dcrpc_proto_msgTypes,
	}.Build()
	File_dcrpc_proto = out.File
	file_dcrpc_proto_goTypes = nil
	file_dcrpc_proto_depIdxs = nil
}
